version: '3.0'

services:

  main_db:
    container_name: main_db
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: utility_bills
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5441:5432"


  test_db:
    container_name: test_db
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: utility_bills
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5442:5432"