spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5441/logistics
    username: root
    password: root
#    jpa:
#      hibernate:
#        ddl-auto: create
